version: '3.3'
services:

  psql:
    image: postgres:alpine
    volumes:
      - pg-data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: abpdock/foodgram
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - ~/data/:/app/data/
    depends_on:
      - psql

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ~/frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

volumes:
  pg-data:
  static_value:
  media_value:
