# Generated by Django 4.1 on 2022-09-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_follow_users_follow_unique_relationships_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_subscribed',
        ),
    ]
